version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    
  # mongodb:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
volumes:
  redis_data: